Microservice implementation
said-mendez/products-task pull request #2
Opened 2023-05-23 15:08 UTC by said-mendez

# What was changed?
- Product database model.
- Product DAO.
- Product service.
- Table and stored procedure migration file.

2023-05-23 15:10 UTC, said-mendez commented on microservice/src/main/java/com/skytouch/microservice/model/ProductDB.java
The idea behind this model is to be used for communication with the DB, so the Product model in the Common Library is the one exposed to the API. If this is good to go, I will add some mappers to concert from Product API model to Product DB model.
Do you think is a good approach?

2023-05-24 13:57 UTC, HerCerM requested changes

2023-05-24 13:57 UTC, HerCerM commented on microservice/src/main/java/com/skytouch/microservice/model/ProductDB.java
> +    @Column
It seems that the `name` value is missing:

 ```suggestion
     @Column(name = "is_deleted")
```

2023-05-24 13:57 UTC, hernancerm commented on microservice/src/main/java/com/skytouch/microservice/service/implementation/ProductServiceImpl.java
> +    public ProductServiceImpl(ProductDao productDao, EntityManager entityManager) {
The `entityManager` is not used in this class. And since the DB interactions are being done through the DAO object, I think this injection can be removed from the constructor

2023-05-24 13:57 UTC, HerCerM commented on microservice/src/main/java/com/skytouch/microservice/service/implementation/ProductServiceImpl.java
> +    public ProductDB addProduct(ProductDB productDB) {
**Optional:** I recommend adding an error log in case the DB interaction fails. Similarly with `fetchAllProducts`. Since you are using Lombok, you can leverage the annotation `@Slf4j`. The stack trace should also be present in the logs. This can add up to the error handling approaches

2023-05-24 13:57 UTC, HerCerM commented on microservice/src/main/java/com/skytouch/microservice/model/ProductDB.java
Yes, I think this is a good approach. The models are separated properly (API model shared in common library and DB model only exists in the microservice) and using a mapper nicely packs the conversion logic

2023-05-24 16:10 UTC, said-mendez commented on microservice/src/main/java/com/skytouch/microservice/service/implementation/ProductServiceImpl.java
> +    public ProductDB addProduct(ProductDB productDB) {
Got it, I will add this error logs, just one question, it would be ok to remove`@Transactional` annotation in the `fetchAllProducts` and `addProduct` service methods?
When I keep the annotation, it seems that the exception can't be catched and the following message is displayed:
Transaction marked as rollbackOnly
But when I remove the `@Transactional` annotation it works fine.

2023-05-24 18:52 UTC, HerCerM commented on microservice/src/main/java/com/skytouch/microservice/service/implementation/ProductServiceImpl.java
> +    public ProductDB addProduct(ProductDB productDB) {
Yes, it's ok to remove the `@Transactional` for this task. Off the top of my head I don't know why the exception can't be caught due to the rollbackOnly

2023-05-25 14:02 UTC, said-mendez commented on microservice/src/main/java/com/skytouch/microservice/service/implementation/ProductServiceImpl.java
> +    public ProductDB addProduct(ProductDB productDB) {
I've added a different response from the service to include status and message details with the data response. Also the log details were added.

2023-05-25 18:01 UTC, hernancerm commented on microservice/src/main/java/com/skytouch/microservice/model/AddProductsRequestResponse.java
> +public class AddProductsRequestResponse {
For adding the products, it's not required to return a response to the management app, as that can be done async. You could also do that communication sync, but async is the preferred approach. However, for getting the list of products, it makes sense to have a response since that has to be sync. This class can remain here, and as the project progresses this class may change or not be needed

2023-05-25 18:02 UTC, HerCerM approved these changes

2023-05-25 18:06 UTC, HerCerM commented on microservice/src/main/java/com/skytouch/microservice/service/implementation/ProductServiceImpl.java
> +    public ProductDB addProduct(ProductDB productDB) {
I left a comment on  the class`AddProductsRequestResponse`, however that does not block the approval. It's a consideration to take into account when implementing the RabbitMQ communication

2023-05-25 18:09 UTC, said-mendez commented on microservice/src/main/java/com/skytouch/microservice/model/AddProductsRequestResponse.java
> +public class AddProductsRequestResponse {
Got it! I will have this in mind when doing the integration.

2023-05-25 19:01 UTC, merged