Management
said-mendez/products-task pull request #3
Opened 2023-06-01 19:46 UTC by said-mendez

# What was changed?
- Add exception handling for Management App.
- Create publisher to add and list products.
- Add error view.
- Complete list products view.
- Add Management App tests.

2023-06-01 22:33 UTC, HerCerM requested changes

2023-06-01 22:33 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/ProductPublisherService.java
> +            throw new RuntimeException("Microservice is not responding!");
Prefer throwing a more specific exception type instead of using the generic `RuntimeException`.

Also, the `throws` keyword at the method definition is generally only used for checked exceptions. So if your new, more specific exception extends `RuntimeException`, there is no need to add it to the method definition

2023-06-01 22:33 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/ProductPublisherService.java
> +            throw new RuntimeException("Microservice is not responding!");
In addition to throwing an exception, I recommend also adding a log statement at ERROR level

2023-06-01 22:33 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/ProductPublisherService.java
> +        ResponseStatus responseStatus = (ResponseStatus) rabbitTemplate.convertSendAndReceive(EXCHANGE, ADD_PRODUCTS_KEY, product);
Instead of using the `RabbitTemplate` method `convertSendAndReceive`, I recommend using `convertAndSend` for this case of adding products. The latter allows you to send the message and don't wait for the microservice to create the product (the async approach). This way, if the microservice is down when a user attempts to create a product, the messages can pile up in the RabbitMQ queue and be processed once the microservice is up again.

<https://docs.spring.io/spring-amqp/api/org/springframework/amqp/rabbit/core/RabbitTemplate.html#convertAndSend(java.lang.Object)>

2023-06-01 22:33 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/ProductPublisherService.java
> +public class ProductPublisherService {
Since this class is coupled to RabbitMQ, a better name could be `ProductServiceRabbitMQ`. You can also create a `ProductService` interface and have this class be an implementation

2023-06-01 22:33 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/ProductPublisherService.java
> +            throw new RuntimeException("Microservice is not responding!");
Please also add a log statement at ERROR level

2023-06-02 14:22 UTC, said-mendez commented on management/src/main/java/com/skytouch/management/service/ProductPublisherService.java
> +        ResponseStatus responseStatus = (ResponseStatus) rabbitTemplate.convertSendAndReceive(EXCHANGE, ADD_PRODUCTS_KEY, product);
Good point it makes sense to me, just that with the approach I took in the project I am not completely sure of how to change from the method `convertSendAndReceive` method to the `convertAndSend`. Currently the use of `convertSendAndReceive` is in order to return from the microservice any error/success messages related to adding a product.
I was researching and found out that a correlation id can be added to track the request, but still I don't understand how to return response to the proper requester/publisher.
I hope we can discuss further in the SC to see what alternatives we have or if I'm missing something.

2023-06-02 14:24 UTC, said-mendez commented on management/src/main/java/com/skytouch/management/service/ProductPublisherService.java
> +            throw new RuntimeException("Microservice is not responding!");
Noted, thanks for the advice.

2023-06-02 16:45 UTC, HerCerM requested changes

2023-06-02 16:45 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/ProductServiceRabbitMQ.java
> +public interface ProductServiceRabbitMQ {
Since this is an interface, a better name would be `ProductService`, since it does not have to be implemented using RabbitMQ

2023-06-02 16:45 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/implementation/ProductServiceRabbitMQImpl.java
> +public class ProductServiceRabbitMQImpl implements ProductServiceRabbitMQ {
After renaming the interface to `ProductService`, then this class can be renamed to `ProductServiceRabbitMQ`

2023-06-02 16:45 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/implementation/ProductServiceRabbitMQImpl.java
> +            log.error("Error calling Microservice: ", "Microservice is not responding!");
The log message can be more specific to the error. The second argument is not required, as the arguments beyond the first one are used for placeholders (e.g. `log.error("E: {}", "boom")` would log `E: boom`).

```suggestion
            log.error("Microservice did not provide a response on products retrieval");
```

2023-06-05 19:42 UTC, HerCerM requested changes

2023-06-05 19:42 UTC, HerCerM commented on management/src/test/java/com/skytouch/management/service/ProductServiceRabbitMQTest.java
> +    @Autowired
Is this `@Autowired` annotation required? From the test runner it seems that the Spring context is not started. If it is not needed it should be removed

2023-06-05 19:45 UTC, HerCerM commented on management/src/main/java/com/skytouch/management/service/implementation/ProductServiceRabbitMQ.java
> +    public void addProduct(Product product) {
Add test case for this method in `ProductServiceRabbitMQTest`

2023-06-05 22:42 UTC, HerCerM approved these changes

2023-06-05 22:46 UTC, merged